/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.photop.sap.gc;

import cn.com.photop.generatecode.action.AwtCodeGenerate;
import cn.com.photop.generatecode.action.CodeGenerate;
import cn.com.photop.generatecode.action.GainMoudleData;
import cn.com.photop.generatecode.model.AWTModule;
import java.awt.Component;
import java.awt.Container;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author jiancheng.zheng
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Code Generator");

        jTabbedPane2.setBounds(50, -20, 5, 5);
        jLayeredPane1.add(jTabbedPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setText("报表名称：");
        jLabel1.setBounds(20, 50, 70, 20);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setText("开发人员：");
        jLabel2.setBounds(20, 110, 70, 15);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setText("邮    箱：");
        jLabel3.setBounds(20, 170, 70, 15);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTextPane1);

        jScrollPane1.setBounds(90, 170, 400, 23);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextPane2.setToolTipText("报表表单名称要以Z或Y开头");
        jScrollPane2.setViewportView(jTextPane2);

        jScrollPane2.setBounds(90, 50, 400, 23);
        jLayeredPane1.add(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane3.setViewportView(jTextPane3);

        jScrollPane3.setBounds(90, 110, 400, 23);
        jLayeredPane1.add(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("基本信息", jLayeredPane1);

        jTabbedPane3.setBounds(50, -20, 5, 5);
        jLayeredPane2.add(jTabbedPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setText("查询界面信息：");
        jLabel4.setBounds(10, 10, 90, 15);
        jLayeredPane2.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        jScrollPane4.setBounds(10, 70, 530, 230);
        jLayeredPane2.add(jScrollPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setText("#第一位字符为#表示注释，分割符：|、#、空格");
        jLabel5.setBounds(30, 50, 300, 20);
        jLayeredPane2.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setText("#名称|P/S类型|表-字段|是否必填");
        jLabel6.setBounds(30, 30, 230, 20);
        jLayeredPane2.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("界面设置", jLayeredPane2);

        jTabbedPane4.setBounds(50, -20, 5, 5);
        jLayeredPane3.add(jTabbedPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setText("显示列表信息：");
        jLabel7.setBounds(10, 10, 110, 15);
        jLayeredPane3.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane5.setViewportView(jTextArea2);

        jScrollPane5.setBounds(10, 50, 530, 250);
        jLayeredPane3.add(jScrollPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setText("#字段名称#表#字段#不显示ALV#是否去零");
        jLabel8.setBounds(30, 30, 270, 15);
        jLayeredPane3.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton4.setText("生成");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.setBounds(160, 350, 57, 23);
        jLayeredPane3.add(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton5.setText("取消");
        jButton5.setBounds(280, 350, 57, 23);
        jLayeredPane3.add(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("列表设置", jLayeredPane3);

        jLabel9.setText("保存路径：");
        jLabel9.setBounds(20, 60, 70, 15);
        jLayeredPane4.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField1.setText("C:\\");
            jTextField1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTextField1ActionPerformed(evt);
                }
            });
            jTextField1.setBounds(90, 60, 360, 21);
            jLayeredPane4.add(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);

            jButton1.setText("浏览");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });
            jButton1.setBounds(470, 60, 60, 23);
            jLayeredPane4.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

            jTabbedPane1.addTab("系统设置", jLayeredPane4);

            jButton6.setText("生成");
            jButton6.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton6ActionPerformed(evt);
                }
            });

            jButton7.setText("取消");
            jButton7.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton7ActionPerformed(evt);
                }
            });

            jMenu1.setText("文件");

            jMenuItem10.setText("生成");
            jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem10ActionPerformed(evt);
                }
            });
            jMenu1.add(jMenuItem10);

            jMenuItem7.setText("退出");
            jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem7ActionPerformed(evt);
                }
            });
            jMenu1.add(jMenuItem7);

            jMenuBar1.add(jMenu1);

            jMenu2.setText("编辑");
            jMenu2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenu2ActionPerformed(evt);
                }
            });

            jMenuItem2.setText("基本信息");
            jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem2ActionPerformed(evt);
                }
            });
            jMenu2.add(jMenuItem2);

            jMenuItem3.setText("界面设置");
            jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem3ActionPerformed(evt);
                }
            });
            jMenu2.add(jMenuItem3);

            jMenuItem4.setText("列表设置");
            jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem4ActionPerformed(evt);
                }
            });
            jMenu2.add(jMenuItem4);

            jMenuItem11.setText("系统设置");
            jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem11ActionPerformed(evt);
                }
            });
            jMenu2.add(jMenuItem11);
            jMenu2.add(jSeparator1);

            jMenuItem5.setText("自动生成模式");
            jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem5ActionPerformed(evt);
                }
            });
            jMenu2.add(jMenuItem5);

            jMenuItem8.setText("导入模板生成");
            jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem8ActionPerformed(evt);
                }
            });
            jMenu2.add(jMenuItem8);

            jMenuItem6.setText("模板下载");
            jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem6ActionPerformed(evt);
                }
            });
            jMenu2.add(jMenuItem6);
            jMenu2.add(jSeparator2);

            jMenuItem9.setText("报表框架下载");
            jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem9ActionPerformed(evt);
                }
            });
            jMenu2.add(jMenuItem9);

            jMenuBar1.add(jMenu2);

            jMenu3.setText("帮助");

            jMenuItem1.setText("关于");
            jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem1ActionPerformed(evt);
                }
            });
            jMenu3.add(jMenuItem1);

            jMenuBar1.add(jMenu3);

            setJMenuBar(jMenuBar1);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(184, 184, 184)
                            .addComponent(jButton6)
                            .addGap(79, 79, 79)
                            .addComponent(jButton7)
                            .addGap(0, 175, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jTabbedPane1)))
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton7)
                        .addComponent(jButton6))
                    .addContainerGap(20, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents
    
    /**
     * 关于的对话框
     * @param evt 
     */
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        AboutOkCancelDialog aboutOkCancelDialog = new AboutOkCancelDialog(null, true);
        aboutOkCancelDialog.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jMenuItem4ActionPerformed
    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton7ActionPerformed
    
    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem7ActionPerformed
    
    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        GainMoudleData gainMoudleData = new GainMoudleData();
        String msg = gainMoudleData.getModleString();
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter txt = new FileNameExtensionFilter("TXT Files (.txt)", "txt");
        jfc.addChoosableFileFilter(txt);
        jfc.setDialogType(JFileChooser.SAVE_DIALOG);
        String defaultName = gainMoudleData.getModleName().toUpperCase();
        JTextField text = getTextField(jfc);
        text.setText(defaultName);
//        jfc.setSelectedFile(new File(defaultName));
//        jfc.setFileFilter(txt);
        int res = jfc.showSaveDialog(this);
//         String dir= jfc.getCurrentDirectory().getName();
        String path = jfc.getSelectedFile().getAbsolutePath();
//        System.out.println("path:" + path);
        if (res == JFileChooser.APPROVE_OPTION) {

//            jfc.setSelectedFile(new File(path + "\\" + defaultName + ".txt"));
            if (!path.toLowerCase().endsWith(".txt")) {
                path = path + ".txt";
            }
//            System.out.println(path);
            jfc.setSelectedFile(new File(path));
            
            File file = jfc.getSelectedFile();
            String message = "";
            if (file.exists()) {//已存在文件
                //显示一个对话框来实现是否覆盖源文件
                int r = JOptionPane.showConfirmDialog(jfc, file + "文件已经存在,是否覆盖!", "文件存在", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                if (r == JOptionPane.YES_OPTION) {
                    //当点关闭，点“是”，要三次才可以保存，再退出！    
                    //保存功能代码 
                    try {
                        BufferedWriter bw = new BufferedWriter(new FileWriter(file));
                        bw.write(msg);
                        bw.flush();
                        bw.close();
                        message = "文件保存成功！";
//                        System.out.println("File Save Finished!");
                    } catch (IOException e) {
                        // TODO Auto-generated catch block                        
                        message = "文件保存失败！";
                        e.printStackTrace();
                    }
                } else if (res == JOptionPane.NO_OPTION) {
                    //当点关闭，按“否”（即不保存时），还会出现一次对话框，要再按一次“否”才退出                    
//                    System.exit(0);
                } else if (res == JOptionPane.CANCEL_OPTION) {
                    //当有文档时，点关闭时弹出对话框，按“取消”则返回，成功                        return;    
                }
            } else {
                try {
                    BufferedWriter bw = new BufferedWriter(new FileWriter(file));
                    bw.write(msg);
                    bw.flush();
                    bw.close();
//                    System.out.println("File Save Finished!");
                    message = "文件保存成功！";
                } catch (IOException e) {
                    // TODO Auto-generated catch block
                    
                    message = "文件保存失败！";
                    e.printStackTrace();
                }
            }
            //提示下载是否成功
            javax.swing.JOptionPane.showConfirmDialog((java.awt.Component) null,
                message, "提示", javax.swing.JOptionPane.DEFAULT_OPTION);
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed
    
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:

        String message = new CodeGenerate().doGenerate();
        javax.swing.JOptionPane.showConfirmDialog((java.awt.Component) null,
                message, "提示", javax.swing.JOptionPane.DEFAULT_OPTION);
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed
    
    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:

        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("打开");
//        FileNameExtensionFilter filter = new FileNameExtensionFilter("jpg与gif图片", "jpg", "gif");
//        fc.setFileFilter(filter);
        FileNameExtensionFilter txt = new FileNameExtensionFilter("TXT Files (.txt)", "txt");
        chooser.setFileFilter(txt);
        int rtn = chooser.showOpenDialog(this);
        
        if (rtn == JFileChooser.APPROVE_OPTION) {
//            Image i = Toolkit.getDefaultToolkit().getImage(chooser.getSelectedFile().getPath());
            //显示出来
//            System.out.println( "文件地址："+chooser.getSelectedFile().getPath() ); 
//            String message = new CodeGenerate().doGenerate(chooser.getSelectedFile().getPath());
            String message = new CodeGenerate().doGenerate(chooser.getSelectedFile().getPath(),jTextField1.getText());
            javax.swing.JOptionPane.showConfirmDialog((java.awt.Component) null,
                    message, "提示", javax.swing.JOptionPane.DEFAULT_OPTION);
        }
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * 点击确定生成AWT的报表
     *
     * @param evt
     */
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        aWTDoGenerate();
        
    }//GEN-LAST:event_jButton6ActionPerformed
    
    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        aWTDoGenerate();
    }//GEN-LAST:event_jMenuItem10ActionPerformed
    
 
    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
               
       
    
    }//GEN-LAST:event_jMenu2ActionPerformed
 
    
    /**
     * 导出框架模板 导入一个zip文件
     * @param evt 
     */
    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        FileSaveJFrame fsjf = new FileSaveJFrame(  );
        fsjf.setVisible( true );
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
         jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("打开");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);//只能选择目录
        int res = chooser.showOpenDialog(this);
        if (res == JFileChooser.APPROVE_OPTION) {
            
            jTextField1.setText( chooser.getSelectedFile().getPath() );
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible( true );
            }
        });
    }
    
    public JTextField getTextField(Container c) {
        JTextField textField = null;
        for (int i = 0; i < c.getComponentCount(); i++) {
            Component cnt = c.getComponent(i);
            if (cnt instanceof JTextField) {
                return (JTextField) cnt;
            }
            if (cnt instanceof Container) {
                textField = getTextField((Container) cnt);
                if (textField != null) {
                    return textField;
                }
            }
        }
        return textField;
    }

    /**
     * AWT代码生成
     */
    private void aWTDoGenerate() {
        AWTModule aWTModule = new AWTModule();
        aWTModule.setAuthor(jTextPane3.getText());
        aWTModule.setEmail(jTextPane1.getText());
        aWTModule.setFileName(jTextPane2.getText());
        aWTModule.setPs_str(jTextArea1.getText());
        aWTModule.setAlv_str(jTextArea2.getText());
        aWTModule.setExp_path(jTextField1.getText()  );
//        System.out.println( "Author:"+jTextPane3.getText() );
//        System.out.println( "Email:"+jTextPane1.getText() );
//        System.out.println( "FileName:"+jTextPane2.getText() );
//        System.out.println( "PS:"+jTextArea1.getText() );
//        System.out.println( "ALV:"+jTextArea2.getText() );
        String message = new AwtCodeGenerate(aWTModule).doGenerate();
        javax.swing.JOptionPane.showConfirmDialog((java.awt.Component) null,
                message, "提示", javax.swing.JOptionPane.DEFAULT_OPTION);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    // End of variables declaration//GEN-END:variables
}
